version: "3.9"

services:
  crm_postgres:
    image: postgres:14
    container_name: crm_postgres
    volumes:
      - ~/.pg/pg_data/crm_:/var/lib/postgresql/data
    env_file:
      - .env
  crm_:
    image: crm_django:latest
    container_name: crm_django
    depends_on:
      - crm_postgres
    volumes:
      - static_volume:/crm_/static
      - media_volume:/crm_/media
    env_file:
      - .env
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate  && gunicorn -b 0.0.0.0:8000 root.wsgi:application"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: crm_nginx
    image: crm_nginx
    volumes:
      - static_volume:/crm_/static
      - media_volume:/crm_/media
    depends_on:
      - crm_
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  static_volume:
  media_volume:

