# Generated by Django 5.0.6 on 2024-06-17 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.CharField(blank=True, max_length=150, verbose_name='ФИО')),
                ('object_name', models.CharField(max_length=30, verbose_name='Объект')),
                ('floor', models.CharField(max_length=30, verbose_name='Этаж')),
                ('square', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='КВ')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('reservation', 'Бронь'), ('purchased', 'Куплено'), ('installment_plan', 'Рассрочка'), ('barter', 'Бартер')], default='active', max_length=20, verbose_name='Статус')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartamets', to='account.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Клиента',
                'verbose_name_plural': 'Клиентов',
            },
        ),
    ]
