# Generated by Django 5.0.6 on 2024-06-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartament',
            name='apartment_number',
            field=models.CharField(max_length=30, verbose_name='Номер квартиры'),
        ),
    ]
